baseURL = "https://c-allergic.github.io/"
title = "Sheldon LI"
locale = "en"
theme = "adritian"

[pagination]
  pagerSize = 5

[outputs]
  page = ["HTML"]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  title = "Sheldon LI"
  description = "Researcher in Image Caption Evaluation & Generation Quality Evaluation"
  themeColor = "#478079"
  colorScheme = "slate"
  homepageExperienceCount = 3

  [params.seo]
    siteName = "Sheldon LI"
    siteDescription = "Researcher in Image Caption Evaluation & Generation Quality Evaluation at HKUST(GZ)"

  [params.seo.person]
    name = "Xiaofeng Li"
    url = "https://c-allergic.github.io"
    sameAs = ["https://github.com/c-allergic"]
    sections = ["showcase", "about", "blog"]

  [params.favicons]

  [params.analytics]
    vercelPageInsights = false
    vercelAnalytics = false
    [params.analytics.googleAnalytics]
      code = ""
      enabled = false
    [params.analytics.googleTagManager]
      code = ""
      enabled = false

  [params.colorTheme.selector.disable]
    footer = true
    header = false
    mobileHeader = false

  [params.navbarOverflow]
    mode = "dropdown"

  [params.blog]
    layout = "default"
    narrowContent = true
    showCategories = true
    showRecentPosts = true
    recentPostCount = 5
    listStyle = "summary"

  [params.sharing]
    bluesky = false
    mastodon = false

  [params.plugins]
    [[params.plugins.css]]
      URL = "css/adritian-icons.css"
    [[params.plugins.js]]
      URL = "js/rad-animations.js"
    [[params.plugins.js]]
      URL = "js/sticky-header.js"
    [[params.plugins.js]]
      URL = "js/library/fontfaceobserver.js"
    [[params.plugins.scss]]
      URL = "scss/adritian.scss"

[languages]
  [languages.en]
    disabled = false
    locale = "en"
    direction = "ltr"
    label = "English"
    title = ""
    weight = 0

    [[languages.en.menus.header]]
      name = "Home"
      URL = "/"
      weight = 1
    [[languages.en.menus.header]]
      name = "Blog"
      URL = "/blog"
      weight = 2
    [[languages.en.menus.header]]
      name = "GitHub"
      URL = "https://github.com/c-allergic"
      weight = 3

    [[languages.en.menus.footer]]
      name = "Home"
      URL = "/"
      weight = 1
    [[languages.en.menus.footer]]
      name = "Blog"
      URL = "/blog"
      weight = 2

[build]
  writeStats = true
  [build.buildStats]
    enabledFor = ["scss"]
    disableClasses = false
    disableIDs = false
    disableTags = false
    enable = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    lineNos = false
    noClasses = false
    style = "github"

[imaging]
  resampleFilter = "Lanczos"
  quality = 85
  anchor = "Smart"
